# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-30 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_auto_20180930_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descripcion',
            new_name='title',
        ),
    ]
